enabled: true
debug: false

# Enchantment Names and Abbreviations
# Abbreviations must keep to alphabetical characters!
enchantDetails:
  - enchant: "PROTECTION_ENVIRONMENTAL"
    name: "Protection"
    abbr: "P"
  - enchant: "PROTECTION_FIRE"
    name: "Fire Protection"
    abbr: "FP"
  - enchant: "PROTECTION_FALL"
    name: "Feather Falling"
    abbr: "FF"
  - enchant: "PROTECTION_EXPLOSIONS"
    name: "Blast Protection"
    abbr: "BP"
  - enchant: "PROTECTION_PROJECTILE"
    name: "Projectile Protection"
    abbr: "PP"
  - enchant: "OXYGEN"
    name: "Respiration"
    abbr: "R"
  - enchant: "WATER_WORKER"
    name: "Aqua Affinity"
    abbr: "AA"
  - enchant: "THORNS"
    name: "Thorns"
    abbr: "T"
  - enchant: "DEPTH_STRIDER"
    name: "Depth Strider"
    abbr: "DS"
  - enchant: "FROST_WALKER"
    name: "Frost Walker"
    abbr: "FW"
  - enchant: "BINDING_CURSE"
    name: "Curse of Binding"
    abbr: "CoB"
  - enchant: "DAMAGE_ALL"
    name: "Sharpness"
    abbr: "S"
  - enchant: "DAMAGE_UNDEAD"
    name: "Smite"
    abbr: "Sm"
  - enchant: "DAMAGE_ARTHROPODS"
    name: "Bane of Athropods"
    abbr: "BoA"
  - enchant: "KNOCKBACK"
    name: "Knockback"
    abbr: "K"
  - enchant: "FIRE_ASPECT"
    name: "Fire Aspect"
    abbr: "FA"
  - enchant: "LOOT_BONUS_MOBS"
    name: "Looting"
    abbr: "L"
  - enchant: "SWEEPING_EDGE"
    name: "Sweeping Edge"
    abbr: "SE"
  - enchant: "DIG_SPEED"
    name: "Efficiency"
    abbr: "E"
  - enchant: "SILK_TOUCH"
    name: "Silk Touch"
    abbr: "ST"
  - enchant: "DURABILITY"
    name: "Unbreaking"
    abbr: "U"
  - enchant: "LOOT_BONUS_BLOCKS"
    name: "Fortune"
    abbr: "F"
  - enchant: "ARROW_DAMAGE"
    name: "Power"
    abbr: "Po"
  - enchant: "ARROW_KNOCKBACK"
    name: "Punch"
    abbr: "Pu"
  - enchant: "ARROW_FIRE"
    name: "Flame"
    abbr: "Fl"
  - enchant: "ARROW_INFINITE"
    name: "Infinite"
    abbr: "I"
  - enchant: "LUCK"
    name: "Luck of the Sea"
    abbr: "LS"
  - enchant: "LURE"
    name: "Lure"
    abbr: "Lu"
  - enchant: "MENDING"
    name: "Mending"
    abbr: "M"
  - enchant: "VANISHING_CURSE"
    name: "Curse of Vanishing"
    abbr: "CoV"